#!/command/with-contenv sh

UNOCONVERT_BIN="${UNOCONVERT_BIN:-/usr/bin/unoconvert}"
UNOCONVERT_TIMEOUT="${UNOCONVERT_TIMEOUT:-0s}"

set -xe
unoserver-rest-api \
    --unoconvert-bin "$UNOCONVERT_BIN" \
    --unoconvert-timeout "$UNOCONVERT_TIMEOUT"
